name: Trigger auto deployment for cloudcomputing-chatbot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cloudcomputing-chatbot-AutoDeployTrigger-eacdc684-bd26-4003-bafe-2b5c717b3d24.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLOUDCOMPUTINGCHATBOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLOUDCOMPUTINGCHATBOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLOUDCOMPUTINGCHATBOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: pchatbot.azurecr.io
          registryUsername: ${{ secrets.CLOUDCOMPUTINGCHATBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLOUDCOMPUTINGCHATBOT_REGISTRY_PASSWORD }}
          containerAppName: cloudcomputing-chatbot
          resourceGroup: 7940project
          imageToBuild: pchatbot.azurecr.io/cloudcomputing-chatbot:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


